### ISSUE TITLE
Maintainer gesucht

### ISSUE THREAD

**Issue by SanJSp** [SanJSp/lets_git_reisefuehrer#2]
Da ich nicht alle Probleme für mehr als 8000 Kursteilnehmer lösen kann, bräuchte ich Unterstützung beim Organisieren der Let's Git Repositories. Dabei freue ich mich über Vorschläge, wie man das alles organisieren kann und wenn sich freiwillige melden.

Bitte schlagt etwas vor oder meldet euch bereit zu helfen.

**Comment by Combot0** [comment]
Was wären denn so die typischen Aufgaben des Maintainers? 

Ich hätte als Vorschlag zur Organisation, dass ein Projekt anlegt wird, in dem man dann per Kanban Board sehen kann, in welchem Status sich die Issues befinden. Ob dieses bereits von jemanden bearbeitet wird oder noch offen ist.

**Comment by SanJSp** [comment]
Hi @Combot0 

die Aufgabe eines Maintainers wäre eben solche Dinge zu verwalten. Außerdem wünsche ich mir von Maintainern, dass diese Pull Requests prüfen und dann mergen. Sozusagen möchte ich auch die Lernmöglichkiet bieten, die Führung dieses Projekts (im Team) zu übernehmen.

Hoffentlich hilft das weiter, wenn nicht gerne nachhaken.

Liebe Grüße  
Sandro

**Comment by Combot0** [comment]
Hi @SanJSp 

vielen Dank für die Rückmeldung. Ich würde gern die Rolle übernehmen und so das Projekt unterstützen und mich etwas weiterzubilden 😄. 

Viele Grüße
Stefan

**Comment by SanJSp** [comment]
Ich würde dich jetzt nur als Maintainer beim Kochbuch einführen, damit auch anderen noch diese Rolle bleibt. Falls niemand mehr kommt, kannst du das aber auch gerne übernehmen.

LG
Sandro

**Comment by winnewoerp** [comment]
Bin gerne Maintainer für den Reiseführer, falls noch Bedarf besteht.

**Comment by Jannik-R** [comment]
Ich hätte ebenfalls Interesse mitzuwirken.

**Comment by SanJSp** [comment]
Hallo @Jannik-R und @winnewoerp 

vielen Dank für euren Einsatz. Ich werde euch die nächsten Tage zum Maintainern ernennen.

Liebe Grüße  
Sandro

**Comment by SanJSp** [comment]
Ist gemacht.
