### ISSUE TITLE
Bitte Schweiz hinzufügen

### ISSUE THREAD

**Issue by PeterGyger** [SanJSp/lets_git_reisefuehrer#31]
Im Verzeichnis "Europ" hat es die Ordner "Deutschland" und "Österreich".  

Als Pull Request werde ich ein weiteres Verzeichnis "Schweiz" einfügen.  
Darin einen weiteren Ordner mit dem Namen "kt_bern". Darin lege ich ein Verzeichnis "thun" an.
In diesem Verzeichnis liegen alle Dateien zum Ausflugsziel "Thun".

**Comment by Jannik-R** [comment]
Der Ordner wird angelegt, sobald ein Ort aus der Schweiz beschrieben wird.
Dies kann dann derjenige, der den ersten Ort von der Schweiz anlegt selber erledigen.
