### ISSUE TITLE
Hamburg hinzufügen

### ISSUE THREAD

**Issue by cofw** [SanJSp/lets_git_reisefuehrer#38]
Ort: Hamburg
Land: Deutschland
Kontinent: Europa
Infos: Informationen zu interesannten Sehenswürdigkeiten oder Lokations

**Comment by MPProj** [comment]
Hallo cofw, 

der Ort **Hamburg** ist bereits erstellt, allerdings ist er fälschlicherweise nicht im Unterverzeichnis **Deutschland**, sondern in der darüberliegenden Ebene **Europa** abgelegt.

Ist Dein Issue damit geschlossen, oder soll auch noch die Verschiebung in das korrekte Unterverzeichnis erfolgen?

Danke und Gruss
Mark
