### ISSUE TITLE
Ordner Italien in Ordner Europa einfügen

### ISSUE THREAD

**Issue by GioBor** [SanJSp/lets_git_reisefuehrer#39]
Bitte für Italien einen Ordner im Ordner Europa einfügen, damit dort auch italienische Städte beschreiben werden könne.
Danke!

**Comment by Jannik-R** [comment]
Der Ordner wird angelegt, sobald ein Ort aus Italien beschrieben wird. 
Dies kann dann derjenige, der den ersten Ort von Italien anlegt selber erledigen.

**Comment by Jannik-R** [comment]
Der Ordner wird angelegt, sobald ein Ort aus Italien beschrieben wird.
Dies kann dann derjenige, der den ersten Ort von Italien anlegt selber erledigen.
